### ISSUE TITLE
Challenge 3 (Dice Game): running `yarn deploy` results in a reverted transaction in hardhat logs

### ISSUE THREAD

**Issue by 0xNeshi** [scaffold-eth/se-2-challenges#195]
Repro steps:
- follow the setup steps in Checkpoint 0 of the [Dice Game challenge](https://speedrunethereum.com/challenge/dice-game)
- open 1st terminal
- run `yarn chain`
- open 2nd terminal
- run `yarn deploy`
- **error appears in the former terminal (see below)** 

```console
eth_call
  Contract call:       DiceGame#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at DiceGame.<unrecognized-selector> (contracts/DiceGame.sol:6)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async HardhatNode.runCall (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:713:20)
      at async EthModule._callAction (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:365:9)
      at async HardhatNetworkProvider._sendWithLogging (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:145:22)
      at async HardhatNetworkProvider.request (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:122:18)
      at async JsonRpcHandler._handleRequest (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:191:20)
      at async JsonRpcHandler._handleSingleRequest (/home/nenad/repos/speedrunethereum/challenge-3-dice-game/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:152:17)
```

Address `0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266` (from) seems to be the deployer address (created by hardhat as the `Account #0` (it is also later used by the frontend as the faucet address).
Address `0x5fbdb2315678afecb367f032d93f642f64180aa3` is the address to which `DiceGame` contract is deployed.

**Comment by rin-st** [comment]
Cannot reproduce. Is it prevented you from completing the challenge?

**Comment by 0xNeshi** [comment]
@rin-st the challenge can still be completed. If you are unable to repro, then it might something wrong with my machine's config.
Will close, and if anyone else experiences the same problem, we can reopen
